language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  
env:
  - DJANGO="Django==1.9"
  - DJANGO="Django==1.8.7"
 
matrix:
  exclude:
    - env: DJANGO="Django==1.9"
      python: 3.2
      python: 3.3

install:
  - pip install $DJANGO
  - pip install factory-boy
  - pip install pytz
  - pip install coveralls
  - python setup.py develop

script:
  - cd example_project; coverage run manage.py test photologue

after_success:
  - coveralls

